apiVersion: v1
kind: Service

metadata:
  name: ecommers-frontend-service
  namespace: ecommerce

spec:
  selector:
    app: ecommers-frontend

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: NodePort
