apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-stable
  namespace: ecommerce

spec:
  replicas: 9

  selector:
    matchLabels:
      app: canary-backend

  template:
    metadata:
      labels:
        app: canary-backend
        version: stable

    spec:
      containers:
      - name: nginx
        image: nginx
