apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-canary
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: canary-backend

  template:
    metadata:
      labels:
        app: canary-backend
        version: canary

    spec:
      containers:
      - name: nginx
        image: nginx
