apiVersion: apps/v1
kind: Deployment

metadata:
  name: ecommerce-backend
  namespace: ecommerce

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ecommerce-backend

  template:
    metadata:
      labels:
        app: ecommerce-backend

    spec:
      containers:
        - name: ecommerce-backend
          image: rahulpallavi/ecommerce-backend:latest

          ports:
            - containerPort: 3000

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-backend-config
                  key: PORT

            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-backend-config
                  key: NODE_ENV

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-backend-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-backend-secret
                  key: DB_PASSWORD

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: ecommerce-backend-secret
                  key: JWT_SECRET

          volumeMounts:
            - name: ecommerce-storage
              mountPath: /data

      volumes:
        - name: ecommerce-storage
          persistentVolumeClaim:
            claimName: ecommerce-backend-pvc