apiVersion: v1
kind: Secret

metadata:
  name: ecommerce-backend-secret
  namespace: ecommerce

type: Opaque

data:
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: cGFzc3dvcmQxMjM=
  JWT_SECRET: ZWNvbW1lcmNlLWp3dC1zZWNyZXQ=
