apiVersion: v1
kind: Service

metadata:
  name: ecommerce-backend-service
  namespace: ecommerce

spec:
  selector:
    app: ecommerce-backend

  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.port }}

  type: {{ .Values.backend.service.type }}