apiVersion: v1
kind: Pod

metadata:
  name: oomkill-demo
  namespace: ecommerce

spec:
  containers:
  - name: memory-hog
    image: polinux/stress

    resources:
      requests:
        memory: "50Mi"
      limits:
        memory: "100Mi"

    command:
      - stress

    args:
      - "--vm"
      - "1"
      - "--vm-bytes"
      - "200M"
      - "--vm-hang"
      - "1"


# OOM = Out Of Memory

# How do you troubleshoot OOMKilled?

# Answer:

# 1. Check pod status
# 2. Describe pod
# 3. Verify Last State
# 4. Confirm OOMKilled reason
# 5. Check memory usage using:
#    kubectl top pod
# 6. Review requests and limits
# 7. Increase memory limit or optimize application